### PR TITLE
Support memcached component

### PR DESCRIPTION
**Pull request by kilingzhang**
Support memcached component 
Support key :
set|add|replace|append|prepend|cas|get|gets|delete|incr|decr|stats|flush_all

### CODE REVIEW

**Comment by heyanlong** [comment]
Is there a test screenshot?

**Comment by kilingzhang** [comment]
> Is there a test screenshot?

test agent data 

```

{
    "application_instance":24,
    "uuid":"e4e35b42-5124-4c5a-ab61-9f1bfb384724",
    "pid":3013,
    "application_id":24,
    "version":6,
    "segment":{
        "traceSegmentId":"24.3023.15869688500002",
        "isSizeLimited":0,
        "spans":[
            {
                "tags":{
                    "url":"/"
                },
                "spanId":0,
                "parentSpanId":-1,
                "startTime":1586968850317,
                "operationName":"/",
                "peer":"127.0.0.1:8888",
                "spanType":0,
                "spanLayer":3,
                "componentId":2,
                "refs":[

                ],
                "endTime":1586968850323,
                "isError":0
            },
            {
                "spanId":1,
                "parentSpanId":0,
                "startTime":1586968850317,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->addServer",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"localhost",
                    "memcached.command":"addserver localhost 11211"
                },
                "endTime":1586968850317,
                "isError":0
            },
            {
                "spanId":2,
                "parentSpanId":0,
                "startTime":1586968850317,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->setOption",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"-1001",
                    "memcached.command":"setoption -1001"
                },
                "endTime":1586968850317,
                "isError":0
            },
            {
                "spanId":3,
                "parentSpanId":0,
                "startTime":1586968850317,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->set",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"set_test",
                    "memcached.command":"set set_test set_value"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":4,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->get",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"set_test",
                    "memcached.command":"get set_test"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":5,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->add",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"add_test",
                    "memcached.command":"add add_test add_value"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":6,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->replace",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"set_test",
                    "memcached.command":"replace set_test replace_value 1000"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":7,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->append",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"set_test",
                    "memcached.command":"append set_test _append_value"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":8,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->prepend",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"set_test",
                    "memcached.command":"prepend set_test prepend_value_"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":9,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->increment",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"increment_test",
                    "memcached.command":"increment increment_test 1"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":10,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->decrement",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"decrement_test",
                    "memcached.command":"decrement decrement_test 1"
                },
                "endTime":1586968850318,
                "isError":0
            },
            {
                "spanId":11,
                "parentSpanId":0,
                "startTime":1586968850318,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getStats",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"getstats"
                },
                "endTime":1586968850319,
                "isError":0
            },
            {
                "spanId":12,
                "parentSpanId":0,
                "startTime":1586968850319,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getAllKeys",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"getallkeys"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":13,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getMulti",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"["set_test","add_test"]",
                    "memcached.command":"getmulti ["set_test","add_test"]"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":14,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getServerList",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"getserverlist"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":15,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->delete",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"2333",
                    "memcached.command":"delete 2333"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":16,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->flush",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"flush"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":17,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->flushBuffers",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"flushbuffers"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":18,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getServerList",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"getserverlist"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":19,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getVersion",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"getversion"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":20,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->set",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"int",
                    "memcached.command":"set int 99"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":21,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->set",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"string",
                    "memcached.command":"set string a simple string"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":22,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->set",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"array",
                    "memcached.command":"set array [11,12] 10000"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":23,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->getDelayed",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"["int","array"]",
                    "memcached.command":"getdelayed ["int","array"] 1"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":24,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->fetchAll",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.command":"fetchall"
                },
                "endTime":1586968850322,
                "isError":0
            },
            {
                "spanId":25,
                "parentSpanId":0,
                "startTime":1586968850322,
                "spanType":1,
                "spanLayer":1,
                "componentId":36,
                "operationName":"Memcached->get",
                "peer":"",
                "tags":{
                    "db.type":"memcached",
                    "memcached.key":"set_test",
                    "memcached.command":"get set_test"
                },
                "endTime":1586968850322,
                "isError":0
            }
        ]
    },
    "globalTraceIds":[
        "24.3023.15869688500002"
    ]
}

```

image
image

**Comment by heyanlong** [comment]
Is it possible to get the peer?

**Comment by kilingzhang** [comment]
> Is it possible to get the peer?

The memcached extension has no directly exposed methods to access the resource .  may be hard to implement  .

**Pull request merged**
