### PR TITLE
Replace pthread_create with fork.

### PR DESCRIPTION
**Pull request by jmjoy**
Fix <https://github.com/SkyAPM/SkyAPM-php-sdk/issues/502>.

### CODE REVIEW

**Comment by heyanlong** [comment]
Does the child process exit then the main process exits?

**Comment by jmjoy** [comment]
> Does the child process exit then the main process exits?

Yes, but the reporting to skywalking server is not work.

**Comment by heyanlong** [comment]
Why, I saw the e2e test passed

**Comment by jmjoy** [comment]
> Why, I saw the e2e test passed

我把`exits`看成`exists`了😂，子进程退出了，父进程依然存在，只是子进程变成了僵尸进程，并且无法上报到skywalking server。

**Comment by heyanlong** [comment]
LGTM

**Pull request merged**
