### PR TITLE
支持 LaravelS

### PR DESCRIPTION
**Pull request by cyhii**
LaravelS: https://github.com/hhxsv5/laravel-s

### CODE REVIEW

**Comment by heyanlong** [comment]
what is laravel-s ?

**Comment by heyanlong** [comment]
Please check CI

**Comment by cyhii** [comment]
> Please check CI

看起来是软件源的问题？可以重试下么

`Get:42 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main Translation-en [32.4 kB]
Ign:43 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease
Err:44 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  Release
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 195.135.221.134 443]
Reading package lists...
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  Release' no longer has a Release file.
Error: Process completed with exit code 100.`

**Comment by cyhii** [comment]
> what is laravel-s ?

也是swoole生态的一部分，用来跟Laravel框架做集成的。

**Comment by heyanlong** [comment]
Need update readme.

**Comment by cyhii** [comment]
> Need update readme.

好的，已经更新了。

**Pull request merged**
